# Generated by Django 4.2.1 on 2023-05-30 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
