# Generated by Django 4.2.1 on 2023-05-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='paragraph_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
