# Generated by Django 4.2.1 on 2023-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=918)),
                ('subject', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
