# Generated by Django 4.2.1 on 2023-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me', '0002_contactdata_delete_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='full_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='message',
            field=models.TextField(blank=True, max_length=918, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='subject',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
